const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const html=fs.readFileSync('docs/total.html','utf8');
const scripts=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)];
for(const [i,m] of scripts.entries())if(!/application\/json/.test(m[1]))new vm.Script(m[2],{filename:'total-script-'+i});
const data=JSON.parse(html.match(/id="cm-data">([\s\S]*?)<\/script>/)[1]);
const elements={};
const document={getElementById(id){return elements[id]??=(id==='cm-data'?{textContent:JSON.stringify(data)}:{value:id==='cmB'?'-1':'0',innerHTML:'',textContent:''});},querySelectorAll(){return [];}};
const context=vm.createContext({document,window:{addEventListener(){},scrollTo(){}},location:{hash:''},parent:{},console});
const normalization=html.slice(html.indexOf('function cmNormalizeGroup('),html.indexOf('function cmGroupCls('));
vm.runInContext(normalization,context);
const app=scripts.find(m=>m[2].includes('const CM = JSON.parse'))[2];
vm.runInContext(app,context);
assert(elements.cmSum.innerHTML.includes('5.LLM'));
assert(elements.cmSum.innerHTML.includes('>고객검토</th>'));
assert(!elements.cmSum.innerHTML.includes('6.고객검토'));
assert(!html.includes('<tr><td class="l">6. 고객검토</td>'));
assert(elements.cmF2.innerHTML.includes('6. 고객검토'));
vm.runInContext(`
if(cmNormalizeGroup('5. 원문 보존 (Raw Preservation)')!=='5. LLM')throw Error('Legacy 5');
if(cmNormalizeGroup('6.고객검토')!=='6. 고객검토')throw Error('Category 6');
const header=['확정 여부','등록양식','파트구분','소스 필드 ID','영문 항목명','국문명','가능한 값','데이터 타입','표준화 대상 여부','값 표준 유형','표준화 방법 대분류명','표준화 방법 (세부 메서드)','최종 표준화 방법','이전 표준화 방법','표준화 근거','메모'];
if(cmColMap(header)[10]!==10)throw Error('New header');
header[10]='표준화 방법 5대 대분류명';
if(cmColMap(header)[10]!==10)throw Error('Legacy header');
const make=(id,g)=>['N','BioProject','Part',id,'Field','항목','','text','Y','TEXT',g,'','','','',''];
CM.versions=[{id:'test',date:'2026-09-15',rows:[make('a','5. 원문 보존 (Raw Preservation)'),make('b','5.LLM'),make('c','6.고객검토')]}];
cmInit();
cmSetF(2,'6. 고객검토');
if(document.getElementById('cmCnt').textContent!=='1 / 3개 항목')throw Error('Filter 6');
cmPick('BioProject','',4);
if(!document.getElementById('cmCnt').textContent.startsWith('2 / 3'))throw Error('LLM cell');
cmPick('BioProject','',5);
if(!document.getElementById('cmCnt').textContent.startsWith('1 / 3'))throw Error('Review cell');
`,context);
assert(elements.cmSum.innerHTML.includes('<td>2</td><td>1</td><td>3</td><td>66.7</td>'));
assert(html.includes('kbds-inner-tab'));
assert(html.includes('white-space:pre-wrap'));
console.log('PASS: syntax, legacy mapping, six-category totals, filters, headers, tab bridge, multiline CSS');
